name: Close Pull Requests and Issues

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  reject_pull_requests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
    - name: Reject Pull Request
      run: |
        gh pr review ${{ github.event.pull_request.html_url }} --request-changes --body "This repository is read-only and managed by a bot. Pull requests are not accepted."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  close_pull_requests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: reject_pull_requests
    steps:
    - name: Close Pull Request
      run: |
        gh pr close ${{ github.event.pull_request.html_url }} -c "This repository is read-only and managed by a bot. Pull requests are not accepted."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lock_pull_requests:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: close_pull_requests
    steps:
    - name: Lock Pull Request
      run: |
        gh pr lock ${{ github.event.pull_request.html_url }} -r "resolved"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  close_issues:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
    - name: Close Issue
      run: |
        gh issue close ${{ github.event.issue.html_url }} -c "This repository is read-only and managed by a bot. Issues are not accepted."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lock_issues:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
    - name: Lock Issue
      run: |
        gh issue lock ${{ github.event.issue.html_url }} -r "resolved"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

